name: DeployDotNetCoreWebApp

on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      dotnet-version:
        required: true
        type: string
      app-pool:
        required: true
        type: string
      deployment-target:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ inputs.dotnet-version }} # Specify the exact .NET version
      - name: Build with dotnet
        run: dotnet build ./${{ inputs.project-name }}/${{ inputs.project-name }}.csproj --configuration Release
      - name: Publish with dotnet
        run: dotnet publish ./${{ inputs.project-name }}/${{ inputs.project-name }}.csproj --configuration Release --output ${{ inputs.project-name }}
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-app
          path: ${{ inputs.project-name }}/**
           
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dotnet-app
          path: ${{ inputs.project-name }}
     
      - name: Stop Website
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.AZURE_VM_IP }}
            username: ${{ secrets.AZURE_VM_USERNAME }}
            password: ${{ secrets.AZURE_VM_PASSWORD }}
            port: ${{ secrets.PORT }}
            script: |
                powershell -Command "if ((Get-WebAppPoolState -Name ${{ inputs.app-pool }}).Value -eq 'Started') { Stop-WebAppPool -Name ${{ inputs.app-pool }} } else { Write-Host '${{ inputs.app-pool }} is already stopped.' }"

      - name: Deploy to Azure VM via SSH
        uses: appleboy/scp-action@v0.1.4 # Use a tagged version
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "${{ inputs.project-name }}/*"
          target: ${{ inputs.deployment-target }}

      - name: Start Website
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.AZURE_VM_IP }}
            username: ${{ secrets.AZURE_VM_USERNAME }}
            password: ${{ secrets.AZURE_VM_PASSWORD }}
            port: ${{ secrets.PORT }}
            script: |
              powershell -Command "Start-WebAppPool -Name ${{ inputs.app-pool }}"
