name: BuildAndDeployDotNetCoreWebApp

on:
  workflow_call:
    inputs:
      project-path:
        required: true
        type: string
      dotnet-version:
        required: true
        type: string
      app-pool:
        required: true
        type: string
      deployment-target:
        required: true
        type: string
      unique-name:
        required: true
        type: string

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET ${{ inputs.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Build and Publish ${{ inputs.project-path }} with dotnet
        run: |
          dotnet build ${{ inputs.project-path }} --configuration Release
          dotnet publish ${{ inputs.project-path }} --configuration Release --output publishedWebApp

      - name: Stop Websites belonging to ${{ inputs.app-pool }}
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.AZURE_VM_IP }}
            username: ${{ secrets.AZURE_VM_USERNAME }}
            password: ${{ secrets.AZURE_VM_PASSWORD }}
            port: ${{ secrets.PORT }}
            script: |
              powershell -Command "if ((Get-WebAppPoolState -Name ${{ inputs.app-pool }}).Value -eq 'Started') { Stop-WebAppPool -Name ${{ inputs.app-pool }} }"

      - name: Remove Previous Files From ${{ inputs.deployment-target }}
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.AZURE_VM_IP }}
            username: ${{ secrets.AZURE_VM_USERNAME }}
            password: ${{ secrets.AZURE_VM_PASSWORD }}
            port: ${{ secrets.PORT }}
            script: |
              powershell -Command "& { if (Test-Path -Path '${{ inputs.deployment-target }}') { Remove-Item -Path '${{ inputs.deployment-target }}\*' -Recurse -Force } }"

      - name: Deploy to Azure VM via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "publishedWebApp/*"
          target: ${{ inputs.deployment-target }}
          strip_components: 1
          # rm: true

      - name: Start Websites belonging to ${{ inputs.app-pool }}
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.AZURE_VM_IP }}
            username: ${{ secrets.AZURE_VM_USERNAME }}
            password: ${{ secrets.AZURE_VM_PASSWORD }}
            port: ${{ secrets.PORT }}
            script: |
              powershell -Command "Start-WebAppPool -Name ${{ inputs.app-pool }}"
